#!/usr/bin/env bash
#
# P08 preview deployment on Vercel: log in, link the project, point the Preview
# environment at the dedicated catalog TEST project, deploy a preview alias, and
# allow that origin so the processing endpoint can run.
# Generated by the /wizard skill. Run it from a terminal: bash scripts/p08-vercel-preview-wizard.sh
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env.p08-preview}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

REPO=$(cd -- "$(dirname -- "$0")/.." && pwd)
cd "$REPO"
TEST_ENV="$REPO/.env.catalog-test"

# Prefer a globally installed CLI; otherwise run it through npx.
if command -v vercel >/dev/null 2>&1; then
  VERCEL=(vercel)
else
  VERCEL=(npx --yes vercel)
fi

# set_preview_env NAME VALUE upserts a Vercel Preview environment variable.
set_preview_env() {
  local name="$1" value="$2"
  "${VERCEL[@]}" env rm "$name" preview --yes >/dev/null 2>&1 || true
  printf '%s' "$value" | "${VERCEL[@]}" env add "$name" preview >/dev/null
}

# deploy_preview builds locally for the Preview environment and deploys the
# build output, printing the deployment URL.
deploy_preview() {
  "${VERCEL[@]}" pull --yes --environment=preview >/dev/null
  "${VERCEL[@]}" build >/dev/null
  local out url
  out=$("${VERCEL[@]}" deploy --prebuilt --yes)
  url=$(printf '%s\n' "$out" | grep -Eo 'https://[A-Za-z0-9._-]+' | tail -n1)
  [[ -n "$url" ]] || { warn "could not read the deployment URL from vercel deploy output"; return 1; }
  printf '%s' "$url"
}

TOTAL_STAGES=5

banner "P08 preview on Vercel"

# ── Stage 1: log in and link the project ──────────────────────────────────
stage "Vercel: sign in and link the project"
say "The preview must deploy the SvelteKit app to the project that serves production."
say "This wizard deploys with the Vercel CLI; it never touches the production domain or data."
if "${VERCEL[@]}" whoami >/dev/null 2>&1; then
  note "already signed in as $("${VERCEL[@]}" whoami 2>/dev/null | tail -n1)"
else
  step "A browser opens; finish the sign-in and return here."
  "${VERCEL[@]}" login
fi
step "When 'vercel link' asks, choose the team and the StickerLab project named in docs/production-release.md."
"${VERCEL[@]}" link
if [[ -f .vercel/project.json ]]; then
  note "linked: project $(jq -r '.projectId // "?"' .vercel/project.json 2>/dev/null || echo '?')"
else
  warn "no .vercel/project.json; run 'vercel link' manually before re-running this wizard"
fi
pause

# ── Stage 2: point Preview at the dedicated test project ──────────────────
stage "Vercel: Preview env → catalog TEST project"
say "The Preview environment gets the dedicated P53 test project, never production StickerLab."
if [[ -f "$TEST_ENV" ]]; then
  # shellcheck disable=SC1090
  set -a; source "$TEST_ENV"; set +a
  note "read SUPABASE_TEST_URL and SUPABASE_TEST_KEY from .env.catalog-test"
  P08_SUPABASE_URL="${SUPABASE_TEST_URL:-}"
  P08_SUPABASE_KEY="${SUPABASE_TEST_KEY:-}"
else
  open_url "https://supabase.com/dashboard/project/wkmivbdheoynxaqolzdr/settings/api-keys"
  step "Copy the Project URL."
  ask P08_SUPABASE_URL "Project URL:"
  step "Reveal and copy the publishable key (sb_publishable_…); never a secret key."
  ask P08_SUPABASE_KEY "Publishable key:"
fi
[[ -n "${P08_SUPABASE_URL:-}" && -n "${P08_SUPABASE_KEY:-}" ]] || {
  warn "missing test-project URL or publishable key; re-run with .env.catalog-test present"
  exit 1
}
set_preview_env VITE_SUPABASE_URL "$P08_SUPABASE_URL"
set_preview_env VITE_SUPABASE_PUBLISHABLE_KEY "$P08_SUPABASE_KEY"
write_env P08_SUPABASE_URL "$P08_SUPABASE_URL"
note "publishable key stored in Vercel Preview env (not written to disk)"
pause

# ── Stage 3: stable alias + first deploy ──────────────────────────────────
stage "Vercel: first preview deploy with a stable alias"
say "The endpoint validates the exact request origin, so the preview needs a fixed URL."
P08_PREVIEW_ALIAS="${P08_PREVIEW_ALIAS:-stickerlab-p08.vercel.app}"
ask P08_PREVIEW_ALIAS "Stable preview alias (must be globally unique under vercel.app):"
say "Building locally and deploying the prebuilt output…"
FIRST_URL=$(deploy_preview)
"${VERCEL[@]}" alias set "$FIRST_URL" "$P08_PREVIEW_ALIAS" >/dev/null
write_env P08_PREVIEW_URL "https://$P08_PREVIEW_ALIAS"
note "deployed $FIRST_URL"
note "stable origin: https://$P08_PREVIEW_ALIAS"
pause

# ── Stage 4: allow the alias origin and redeploy ──────────────────────────
stage "Vercel: allow the preview origin and redeploy"
say "VITE_AUTH_ALLOWED_ORIGINS must name the stable alias exactly, or the endpoint stays unconfigured."
set_preview_env VITE_AUTH_ALLOWED_ORIGINS "https://$P08_PREVIEW_ALIAS"
SECOND_URL=$(deploy_preview)
"${VERCEL[@]}" alias set "$SECOND_URL" "$P08_PREVIEW_ALIAS" >/dev/null
say "Verifying that the server function exists on the preview…"
CODE=$(curl -s -o /dev/null -w '%{http_code}' -X POST "https://$P08_PREVIEW_ALIAS/api/catalog/process" \
  -H 'content-type: application/json' --data '{"jobId":"00000000-0000-4000-8000-000000000000"}')
say "POST /api/catalog/process without a token → HTTP $CODE (401/403 expected; 404 means a static-only deployment)."
if [[ "$CODE" == "404" ]]; then
  warn "the endpoint is missing: the deployment is not a server build, so P08 cannot be verified"
fi
pause

# ── Stage 5: keep the repository clean ────────────────────────────────────
stage "Repository: no unintended dependency changes"
if git diff --quiet -- package.json package-lock.json; then
  note "package.json / package-lock.json unchanged"
else
  if git diff -- package.json | grep -q '"vercel"'; then
    warn "npx added 'vercel' to package.json; reverting that unintended dependency"
    git checkout -- package.json package-lock.json
  else
    warn "package.json / package-lock.json changed; inspect them before committing"
  fi
fi
pause

finish
printf '%s  Next:%s run the P08 flow (the agent does this) against %s\n' "$BOLD" "$RESET" "${P08_PREVIEW_URL:-https://$P08_PREVIEW_ALIAS}"
printf '  P08_PREVIEW_URL is saved in %s (gitignored)\n\n' "$ENV_FILE"
